#!/bin/bash

echo "start of script"

if [ "$1" == "--set" ]; then
    # Exit if any command returns nonzero
    set -e
    cd nonexistenterrordir
elif [ "$1" == "--exit" ]; then
    # Manually exit
    cd nonexistenterrordir
    exit 1
fi

echo "end of script"

