#!/bin/bash
# Handles backup of config files

DIR=/home/$USER/code
CONFIG=$DIR/Linux-Config
BACKUP=$DIR/config
TARBALL=configs.tar.gz

# End dir
mkdir $BACKUP
if [ -e "$TARBALL" ]; then
    echo "deleting existing tarball"
    rm $TARBALL
fi

# Bash configs
cp -a $CONFIG/.bash_aliases $BACKUP
cp -a $CONFIG/.bash_motd $BACKUP
cp -a $CONFIG/.bashrc $BACKUP

# Other configs
cp -a $CONFIG/fox.cow $BACKUP
cp -a $CONFIG/.gitconfig $BACKUP
cp -a $CONFIG/.vimrc $BACKUP
cp -a $CONFIG/*.sublime-settings $BACKUP
cp -a $CONFIG/KDE4_keymap.kksrc $BACKUP
cp -a $CONFIG/KDE5_keymap.kksrc $BACKUP

# External configs
cp -a $DIR/External/molokai/colors/molokai.vim $BACKUP
cp -a $DIR/External/Hack/build/ttf/* $BACKUP
cp -a $DIR/Shell-Scripts/Bash/firstboot $BACKUP

sleep 0.1
tar czvf $TARBALL -C $DIR config
rm -r $BACKUP
