#!/bin/bash
# Handles backup of config files

WORKING_DIR=/home/$USER/code
CONFIG=$WORKING_DIR/Linux-Config
BACKUP=$WORKING_DIR/configs
TARFILE=configs.tar.gz

# End dir
mkdir $BACKUP
if [ -e "$TARFILE" ]; then
    echo "deleting existing tarball"
    rm $TARFILE
fi

# Bash configs
cp -a $CONFIG/.bash_aliases $BACKUP
cp -a $CONFIG/.bash_motd $BACKUP
cp -a $CONFIG/.bashrc $BACKUP

# Other configs
cp -a $CONFIG/fox.cow $BACKUP
cp -a $CONFIG/.gitconfig $BACKUP
cp -a $CONFIG/.vimrc $BACKUP
cp -a $CONFIG/inputrc $BACKUP
cp -a $CONFIG/*.sublime-settings $BACKUP
cp -a $CONFIG/KDE4_keymap.kksrc $BACKUP
cp -a $CONFIG/KDE5_keymap.kksrc $BACKUP

# External configs
cp -a $WORKING_DIR/External/molokai/colors/molokai.vim $BACKUP
cp -a $WORKING_DIR/External/Hack/build/ttf/* $BACKUP
cp -a $WORKING_DIR/Scripts/Bash/firstboot $BACKUP

sleep 0.1
tar czvf $TARFILE -C $WORKING_DIR configs
rm -r $BACKUP
