#!/bin/bash
# Sets up a machine by executing essential preparations after it's first boot
# 
# Sets up dirs and symlinks
# Install repositories and packages
#
# Prequisite
# Data dir should already exist

# Where is data stored?
# If /data exists, then a separate mount has been created
# Else, use home directory
# if [ -d "/data" ]; then
#     ln -s /data ~/Data
# fi
DATA=/home/$USER/Data

# Commonly accessed dirs
ln -s $DATA/Dropbox ~/Dropbox
ln -s ~/Dropbox/Code/ ~/code
ln -s ~/Dropbox/Code/Scripts/Bash/ ~/bin
ln -s $DATA/dev ~/dev
ln -s $DATA/vm/ ~/vmware

# Libraries
rm -r $HOME/Documents
rm -r $HOME/Downloads
rm -r $HOME/Music
rm -r $HOME/Pictures
rm -r $HOME/Videos

# If not existing
# mkdir -p $DATA/Documents
# mkdir -p $DATA/Downloads
# mkdir -p $DATA/Music
# mkdir -p $DATA/Pictures
# mkdir -p $DATA/Videos

ln -s $DATA/Documents $HOME/Documents
ln -s $DATA/Downloads $HOME/Downloads
ln -s $DATA/Music $HOME/Music
ln -s $DATA/Pictures $HOME/Pictures
ln -s $DATA/Videos $HOME/Videos

# Torrent dirs
mkdir -p $DATA/Torrent/down
mkdir -p $DATA/Torrent/fin
mkdir -p $DATA/Torrent/srcdown
mkdir -p $DATA/Torrent/srcfin
mkdir -p $DATA/Torrent/srcload

# vim molokai
# mkdir -p ~/.vim/colors
# cp $molokaiorigin ~/.vim/colors

# cowsay
# sudo cp fox.cow /usr/share/cowsay/cows/

# USERLIBS=( Music Pictures Videos Documents Downloads )
# ARRAY_SIZE=${#USERLIBS[@]}
# let "i=0"
# while [ $i -ne $ARRAY_SIZE ]; do
#     DIR=${USERLIBS[$i]}
#     rm -r $HOME/$DIR
#     ln -s $DATA/$DIR $HOME/$DIR
#     let "i++"
# done

# General
sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
sudo apt install vim fortune cowsay fortunes fortunes-debian-hints fortunes-off fortunes-spam fortunes-ubuntu-server lolcat htop atop whois finger tree traceroute openvpn curl hping3 lynx-cur git fonts-hack-ttf libnotify-bin sox libsox-fmt-mp3 scanmem python-software-properties software-properties-common gpart gparted sublime-text-installer synaptic wireshark nikto hydra sqlmap nmap masscan zmap radare2

# Host machine
sudo add-apt-repository -y ppa:jtaylor/keepass
sudo add-apt-repository -y ppa:maarten-baert/simplescreenrecorder
sudo apt install xdotool youtube-dl libav-tools cpufrequtils hexchat vlc keepass2 steam simplescreenrecorder nautilus-dropbox audacity

# VM
sudo apt install ssh open-vm-tools-desktop open-vm-tools-dkms

# Development
sudo add-apt-repository -y ppa:webupd8team/java
sudo add-apt-repository -y ppa:webupd8team/brackets
sudo apt install brackets sqlitebrowser oracle-java8-installer oracle-java8-set-default python3-pip # icedtea-7-plugin flashplugin-installer

# Server
sudo apt install mysql-server mysql-workbench

# Unity
sudo apt install unity-tweak-tool gnome-color-chooser

# XFCE
sudo apt install thunar-dropbox-plugin

# Cinnamon
sudo add-apt-repository ppa:tsvetko.tsvetkov/cinnamon
sudo apt install cinnamon cinnamon-themes mint-backgrounds* nemo-dropbox mint-x-icons mint-themes cinnamon-session

# Python development

sudo -H pip3 install requests[security]

# Chrome
echo "
deb http://dl.google.com/linux/chrome/deb/ stable main
" >> /etc/apt/sources.list
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

# Debian Drivers
function DebDrivers {
    # Add repos
    echo "
    deb http://ftp.de.debian.org/debian/ jessie main non-free contrib
    # deb-src http://ftp.de.debian.org/debian/ jessie main non-free contrib

    deb http://security.debian.org/ jessie/updates main contrib non-free
    # deb-src http://security.debian.org/ jessie/updates main contrib non-free
    " >> /etc/apt/sources.list

    sudo apt firmware-iwlwifi firmware-realtek
}
