#!/bin/bash
# Configure a fresh Linux installation

# Debian Drivers if they're ever needed
function DebDrivers {
    # Add repos
    echo "
    deb http://ftp.de.debian.org/debian/ jessie main non-free contrib
    # deb-src http://ftp.de.debian.org/debian/ jessie main non-free contrib

    deb http://security.debian.org/ jessie/updates main contrib non-free
    # deb-src http://security.debian.org/ jessie/updates main contrib non-free
    " >> /etc/apt/sources.list

    sudo apt update && sudo apt firmware-iwlwifi firmware-realtek
}

# Libraries

DATA=/home/$USER/Data

# Find data dir
if [ -d "/data" ]; then
    ln -s /data ~/Data
    echo "Using /data"
elif [ -d $DATA ]; then
    echo "Using ~/data"
else
    echo "No data directory found, exiting"
    exit 1
fi

# Link to common dirs
ln -s $DATA/vm/ ~/vmware
ln -s $DATA/dev ~/dev
ln -s $DATA/Dropbox ~/Dropbox
ln -s ~/Dropbox/Code/ ~/code

ln -s ~/code/Scripts/Bash/ ~/bin
ln -s ~/code/Scripts/Python ~/py

# Temporary links
ln -s ~/Dropbox/Documents/SJSU/Courses ~/courses
ln -s ~/code/Coursework/CS100W/ ~/100w
ln -s ~/code/Coursework/CS152/ ~/152
ln -s ~/code/Coursework/CS158B/ ~/158b
ln -s ~/code/Coursework/CS185C/ ~/185c

ln -s ~/code/Challenges/Cryptopals ~/crypto
ln -s ~/code/Challenges/Stockfighter ~/stock

# Relocate dirs from ~/ to ~/data
USERLIBS=(
    Documents
    Downloads
    Music
    Pictures
    Videos
)
for DIR in "${USERLIBS[@]}"; do
    # ls -alhF $DIR
    rm -r $HOME/$DIR
    ln -s $DATA/$DIR $HOME/$DIR
done

# Torrent dirs
# mkdir -p $DATA/Torrent/down
# mkdir -p $DATA/Torrent/fin
# mkdir -p $DATA/Torrent/srcdown
# mkdir -p $DATA/Torrent/srcfin
# mkdir -p $DATA/Torrent/srcload

# Configs

CONFIGS=$HOME/code/Linux-Config

# general configs
cp $CONFIGS/.* ~/

# vim
mkdir -p ~/.vim/colors
mv $CONFIGS/molokai.vim ~/.vim/colors

# cowsay
sudo cp $CONFIGS/fox.cow /usr/share/cowsay/cows/

# inputrc
printf '\nset completion-ignore-case On' | sudo -E tee /etc/inputrc > /dev/null

# sublime
wget -P ~/.config/sublime-text-3/Installed\ Packages https://sublime.wbond.net/Package%20Control.sublime-package
cp $CONFIGS/sublime/* ~/.config/sublime-text-3/Packages/User/

# Packages
HOST=true
VM=true
DEV=true
SERV=false
UNITY=false
XFCE=false
CIN=false

REPOS=()
PACKAGES=()
# General
REPOS+=(
    "ppa:webupd8team/sublime-text-3"
)
PACKAGES+=(
    "vim"
    "fortune"
    "cowsay"
    "fortunes"
    "fortunes-debian-hints"
    "fortunes-off"
    "fortunes-spam"
    "fortunes-ubuntu-server"
    "lolcat"
    "htop"
    "atop"
    "whois"
    "finger"
    "tree"
    "traceroute"
    "nmap"
    "openvpn"
    "sshfs"
    "curl"
    "hping3"
    "lynx-cur"
    "git"
    "fonts-hack-otf"
    "libnotify-bin"
    "scanmem"
    "python-software-properties"
    "software-properties-common"
    "gpart"
    "gparted"
    "sublime-text-installer"
    "synaptic"
    "wireshark"
)

# Host machine
if [ $HOST = true ]; then
    REPOS+=(
        "ppa:jtaylor/keepass"
        "ppa:maarten-baert/simplescreenrecorder"
    )
    PACKAGES+=(
        "xdotool"
        "youtube-dl"
        "libav-tools"
        "cpufrequtils"
        "hexchat"
        "vlc"
        "keepass2"
        "steam"
        "simplescreenrecorder"
        "nautilus-dropbox"
        "audacity"
    )
# VM
elif [ $VM = true ]; then
    PACKAGES+=(
        "ssh"
        "open-vm-tools-desktop"
        "open-vm-tools-dkms"
    )
fi

# Development/Security
if [ $DEV = true ]; then
    REPOS+=(
        "ppa:webupd8team/java"
        "ppa:webupd8team/brackets"
        "ppa:gns3/ppa"
    )
    PACKAGES+=(
        # Development
        "oracle-java8-installer"
        "oracle-java8-set-default"
        "icedtea-plugin"
        "icedtea-8-plugin"
        "python3-pip"
        "python3-bs4"
        "python3-requests"
        "python3-crypto"
        "nodejs"
        "npm"
        "node-typescript"
        "brackets"
        "httpie"
        "sqlitebrowser"
        "gns3-gui"
        "gns3-iou"
        # "icedtea-7-plugin"
        # "flashplugin-installer"
        # Security
        "sox"
        "libsox-fmt-mp3"
        "nikto"
        "hydra"
        "sqlmap"
        "masscan"
        "zmap"
        "radare2"
    )
fi

# Server
if [ $SERV = true ]; then
    PACKAGES+=(
        "ssh"
        "mysql-server"
        "mysql-workbench"
    )
fi

# Unity
if [ $UNITY = true ]; then
    PACKAGES+=(
        "unity-tweak-tool"
        "gnome-color-chooser"
    )
# XFCE
elif [ $XFCE = true ]; then
    PACKAGES+=(
        "thunar-dropbox-plugin"
    )
# Cinnamon
elif [ $CIN = true ]; then
    REPOS+=(
        "ppa:tsvetko.tsvetkov/cinnamon"
    )
    PACKAGES+=(
        "cinnamon"
        "cinnamon-themes"
        "mint-backgrounds*"
        "nemo-dropbox"
        "mint-x-icons"
        "mint-themes"
        "cinnamon-session"
    )
fi

for R in "${REPOS[@]}"; do
    echo "sudo add-apt-repository -y "$R
done

SELECTED=""
for P in "${PACKAGES[@]}"; do
    SELECTED+=$P" "
done
echo "sudo apt install "$SELECTED

# Python development
sudo -H pip3 install --upgrade pip3
sudo -H pip3 install setuptools requests[security]
