#!/bin/bash
# Multiple file series retriever

URL_CONTENT="http://content.xanacreations.com/furcast/ep/"
NAME_START="fc-"
NAME_END=".mp3"
DIR=~/wget

START=$1
END=$2
let "CURRENT=$START"
while [ $CURRENT -le $END ]; do
    TITLE=$NAME_START$CURRENT$NAME_END
    URL_FULL=$URL_CONTENT$TITLE
    wget $URL_FULL -P $DIR &
    echo "Started job for $TITLE"
    let "CURRENT++"
done
