#!/bin/bash
# Parallel downloads furcast episodes
# Range of episodes are inclusive, and specified in parameters
# The following will download episodes 1, 2, and 3
# $ bash furcast 1 3

URL_CONTENT="http://content.xanacreations.com/furcast/ep/"
NAME_START="fc-"
NAME_END=".mp3"
DIR=~/wget

START=$1
END=$2
mkdir -p $DIR
let "CURRENT=$START"
while [ $CURRENT -le $END ]; do
    TITLE=$NAME_START$CURRENT$NAME_END
    URL_FULL=$URL_CONTENT$TITLE
    LOG=$DIR/$NAME_START$CURRENT".log"
    touch $LOG
    wget -nv -o $LOG -P $DIR $URL_FULL &
    echo "Started job for $TITLE"
    let "CURRENT++"
done
