#!/bin/bash

# commands:
# init - sets up repository
# pull - updates local files using repo
# push - uses local files to update repo

$DIR=~/config
$REPO=https://github.com/repo

if [ "$1" == "init" ]; then
    echo "initialize repos"
    # cd $DIR
    # git pull $REPO
elif [ "$1" == "-s" ]; then
    echo "update local files"
    git pull $DIR
elif [ "$1" == "-q" ]; then
    echo "update repo with local files"
elif [ "$1" == '--help' ]; then # help text
    echo "Sends update and upgrade commands to apt"
    echo "Options:"
    echo "    -init        "
    echo "    -pull        "
    echo "    -push        "
    echo "    (blank)      "
    echo ""
    echo "All options except silent will print apt update errors"
else
    echo "option '$1' not recognized."
    echo "'--help' for usage information."
fi
