#!/bin/bash
# Multiple file series retriever

# Example:
# http://someURL.com/directory/file-part-1.zip
# http://someURL.com/directory/file-part-2.zip
# ...
# http://someURL.com/directory/file-part-9.zip

# also pass in the parameters 1 and 9 like so:
# bash wgetter 1 9

# Static Variables
# Dir names
DIRS=(
    'Aerosmith'
)
# Where downloads go
PATH='/media/rayting/Volume Echo/HD Backup/Torrents/new'
# Total dirs to create
TOTAL=${#DIRS[@]}

# Get range to download from input parameters
let "i=0"
# create each dir
echo $TOTAL
echo $DIRS
echo $PATH
echo $i
cd /
while [ $i -ne $TOTAL ]; do
    /bin/mkdir -p $PATH/${DIRS[$i]}
    let "i++"
done
