#!/bin/bash
# Parallel downloads TechSNAP episodes
# Range of episodes are inclusive, and specified in parameters
# The following will download episodes 1, 2, and 3
# $ bash techsnap 1 3

URL_CONTENT="http://www.podtrac.com/pts/redirect.mp3/traffic.libsyn.com/jbmirror/"
# jupiterbroadcasting
# jnite
# jbmirror
NAME_START="techsnap-0"
NAME_END=".mp3"
DIR=~/wget

START=$1
END=$2
let "CURRENT=$START"
while [ $CURRENT -le $END ]; do
    TITLE=$NAME_START$CURRENT$NAME_END
    URL_FULL=$URL_CONTENT$TITLE
    LOG=$DIR/$NAME_START$CURRENT".log"
    touch $LOG
    wget -nv -o $LOG -P $DIR $URL_FULL --progress=bar &
    echo "Started job for $TITLE"
    let "CURRENT++"
done
