#!/bin/bash
# Simple script to update packages on machine. Has three output levels:
# Silent only outputs update errors and does NOT ask for upgrade permission
# Verbose outputs everything and asks for permission
# Quiet outputs update errors and upgrade information but does NOT ask for upgrade permission
# Default outputs update error and asks for upgrade permission

if [ "$1" == "" ]; then # Default verbose
    sudo apt update
    apt list --upgradable
    alert
elif [ "$1" == "--upgrade" ]; then # Quiet
    sudo apt upgrade
    alert
elif [ "$1" == '--help' ]; then # help text
    echo "Sends update and upgrade commands to apt"
    echo "Options:"
    echo "    (blank)   ask and output for upgrades only"
    echo ""
    echo "All options except silent will print apt update errors"
else
    echo "option '$1' not recognized."
    echo "'--help' gives usage information."
fi
