#!/bin/bash
# Simple script to update packages on machine. Has three output levels:
# Silent only outputs update errors and does NOT ask for upgrade permission
# Verbose outputs everything and asks for permission
# Default outputs update errors and upgrade information but does NOT ask for upgrade permission

if [ "$1" == "-s" ]; then # Silent
    sudo apt-get update -qq
    sudo apt-get upgrade -qq -y
elif [ "$1" == "-v" ]; then # Verbose
    sudo apt-get update
    sudo apt-get upgrade
elif [ "$1" == "" ]; then # default "quiet" run mode
    sudo apt-get update -qq
    sudo apt-get upgrade -y
elif [ "$1" == '--help' ]; then # help text
    echo "Sends update and upgrade commands to apt"
    echo "Options:"
    echo "    -s        no output and accept upgrades"
    echo "    -v        all outputs and ask for upgrades"
    echo "    (blank)   output for upgrades only"
    echo ""
    echo "All options print apt update errors"
else
    echo "option '$1' not recognized."
    echo "'--help-' gives usage information."
fi

