#!/bin/bash
# Simple script to update packages on machine. Has three output levels:
# Silent only outputs update errors and does NOT ask for upgrade permission
# Verbose outputs everything and asks for permission
# Default outputs update errors and upgrade information but does NOT ask for upgrade permission

if [ "$1" == "-s" ]; then # Silent
    sudo apt-get update -qq
    sudo apt-get upgrade -qq -y
elif [ "$1" == '-v' ]; then # Verbose
    sudo apt-get update
    sudo apt-get upgrade
else # default "quiet" run mode
    sudo apt-get update -qq
    sudo apt-get upgrade -y
fi

