#!/bin/bash
# OpenVPN script
# Connects to vpn via openvpn, includes tools for configuring DNS


DIR=/home/$USER/.vpn # directory for all your config files

#CONFIG=nl01-443-128b.ovpn
#CONFIG=ro01-443-128b.ovpn
#CONFIG=ro-256b.ovpn
#CONFIG=us-128b.ovpn
#CONFIG=us-ca01-128b.ovpn
#CONFIG=us-ca01-443-128b.ovpn
CONFIG=us-443-128b.ovpn

AUTH=login

# DNS
set_dns () {
    printf 'nameserver 8.8.8.8\nnameserver 8.8.4.4\n' | sudo -E tee /etc/resolv.conf > /dev/null
}

# Connect to vpn
vpn_connect () {
    firefox -private whatismyipaddress.com & # Test vpn connection
    sudo openvpn --config $DIR/$CONFIG --auth-user-pass $DIR/$AUTH --auth-nocache;
}

# Default start vpn
if [ "$1" == "" ]; then
    vpn_connect
# prints resolv.conf contents
elif [ "$1" == "-c" ]; then
    cat /etc/resolv.conf
# config dns
elif [ "$1" == "-d" ]; then
    set_dns
# help
elif [ "$1" == "--help" ]; then # help text
    echo "Utilities for connecting to a vpn using OpenVPN"
    echo "Options:"
    echo "    -c        c for cat, cat current resolv.conf"
    echo "    (blank)   connect to vpn and sets dns"
    echo ""
# unknown
else
    echo "option '$1' not recognized."
    echo "'--help' gives usage information."
fi
