#!/bin/bash
# OpenVPN script
# Connects to vpn via openvpn, includes tools for configuring DNS

#CONFIG=nl01-443-128b.ovpn
#CONFIG=ro01-443-128b.ovpn
#CONFIG=ro-256b.ovpn
#CONFIG=us-128b.ovpn
#CONFIG=us-ca01-128b.ovpn
CONFIG=us-ca01-443-128b.ovpn
#CONFIG=us-443-128b.ovpn

AUTH=login
DIR=$HOME/.vpn

# DNS
set_dns () {
    printf 'nameserver 8.8.8.8\nnameserver 8.8.4.4\n' | sudo -E tee /etc/resolv.conf > /dev/null
}

# Connect to vpn
vpn_connect () {
    sudo pwd >> null # get sudo priv
    firefox -private whatismyipaddress.com & # Test vpn connection
    cd $DIR
    sudo openvpn --config "$CONFIG" --auth-user-pass "$AUTH" --auth-nocache &
}

# Default start vpn
if [[ "$1" == "" ]]; then
    vpn_connect
# prints resolv.conf contents
elif [[ "$1" == "-c" ]]; then
    cat /etc/resolv.conf
# config dns
elif [[ "$1" == "-d" ]]; then
    set_dns
# force kill
elif [[ "$1" == "-k" ]]; then
    sudo pkill -KILL vpn
# help
elif [[ "$1" == "--help" ]]; then # help text
    echo "Utilities for connecting to a vpn using OpenVPN"
    echo "Options:"
    echo "    -c        Show current resolv.conf"
    echo "    -d        Change DNS servers to Google's 8.8.8.8 and 8.8.4.4"
    echo "    -k        Kill the vpn connection"
    echo "    (blank)   connect to vpn and without setting dns"
    echo ""
# unknown
else
    echo "option '$1' not recognized."
    echo "'--help' gives usage information."
fi
