#!/bin/bash
# Retrieves entire HTTP directory, with authentication
# Intended to be used as "wgetdirauth example.com MyUsername MyPassword"
# verbose
# 10 levels
# recursive
# output dir
# header

wget -v -l 10 -r -P wget --user=$2 --password=$3 --header="User-Agent: Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11" $1
